### ISSUE TITLE
使用Chrome无法识别到串口

### ISSUE THREAD

**Issue by HoGC** [espressif/esp-launchpad#1]
使用Chrome无法识别到串口，是否需要插件的支持
![image](https://user-images.githubusercontent.com/50402699/176988853-5bb20957-00e8-4e01-a74c-c7cda711b1ff.png)

**Comment by adwait-esp** [comment]
Hello @HoGC  - Can you please elaborate a bit more about this issue? 
What I got using the Google translate of the message is that Chrome browser is unable to detect the USB serial, asking for turning on a plugin?

Can you please check this link - https://support.google.com/chrome/answer/6362090?hl=en&co=GENIE.Platform%3DDesktop

**Comment by igrr** [comment]
Very likely it is the same issue as https://github.com/espressif/esp-launchpad/issues/7#issuecomment-1426663204, I'll close this one as a duplicate.
