### ISSUE TITLE
Link to "Publish your own firmware apps"

### ISSUE THREAD

**Issue by krzychb** [espressif/esp-launchpad#2]
Hi @adwait-esp, I am following instructions [Publish your own firmware apps](https://espressif.github.io/esp-launchpad/#publishDiv).

To check how this functionality works I decided to try couple of `.toml` files in https://github.com/espressif/esp-launchpad/tree/main/config that have different set of application binaries.

Should links below show a drop down with different set of apps?

- https://espressif.github.io/esp-launchpad/?flashConfigURL=https://github.com/espressif/esp-launchpad/blob/main/config/default_config.toml
- https://espressif.github.io/esp-launchpad/?flashConfigURL=https://github.com/espressif/esp-launchpad/blob/main/config/matter_config.toml
- https://espressif.github.io/esp-launchpad/?flashConfigURL=https://github.com/espressif/esp-launchpad/blob/main/config/rainmaker_config.toml

For each link I see dropdown with the same set of binaries.

![image](https://user-images.githubusercontent.com/12953787/187028442-eb3fb9b1-4aa0-4394-8a17-69d2cf695cb9.png)

**Comment by adwait-esp** [comment]
Those should show different set of binaries in the dropdown. Seems a bug. Let me check and respond.

Regards,
Adwait

On 27-Aug-2022, at 5:12 PM, Krzysztof ***@***.******@***.***>> wrote:


[External: This email originated outside Espressif]


Hi @adwait-esp<https://github.com/adwait-esp>, I am following instructions Publish your own firmware apps<https://espressif.github.io/esp-launchpad/#publishDiv>.

To check how this functionality works I decided to try couple of .toml files in https://github.com/espressif/esp-launchpad/tree/main/config that have different set of application binaries.

Should links below show a drop down with different set of apps?

  *   https://espressif.github.io/esp-launchpad/?flashConfigURL=https://github.com/espressif/esp-launchpad/blob/main/config/default_config.toml
  *   https://espressif.github.io/esp-launchpad/?flashConfigURL=https://github.com/espressif/esp-launchpad/blob/main/config/matter_config.toml
  *   https://espressif.github.io/esp-launchpad/?flashConfigURL=https://github.com/espressif/esp-launchpad/blob/main/config/rainmaker_config.toml

For each link I see dropdown with the same set of binaries.

[image]<https://user-images.githubusercontent.com/12953787/187028442-eb3fb9b1-4aa0-4394-8a17-69d2cf695cb9.png>

**Comment by adwait-esp** [comment]
Just checked that the URLs used as query parameter are directly pointing to a file in Github repo. This is resulting in a CORS error as Github directly doesn't support cross domain GET calls from the browser. Instead the path to your TOML should be over a webserver which supports CORS requests. The hosted Github pages do work well in this case.

If you want to try the URLs instead can you try these?

https://espressif.github.io/esp-launchpad/?flashConfigURL=https://espressif.github.io/esp-launchpad/config/matter_config.toml
https://espressif.github.io/esp-launchpad/?flashConfigURL=https://espressif.github.io/esp-launchpad/config/rainmaker_config.toml

You should see subset of the binaries in the list

**Comment by krzychb** [comment]
Using links to configuration files hosted an GitHub pages work correctly. Thank you @adwait-esp!
