### ISSUE TITLE
DevTools failed to load source map: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### ISSUE THREAD

**Issue by leeebo** [espressif/esp-launchpad#20]
It worked fine two days ago, but now it has a problem with download

```
DevTools failed to load source map: Could not load content for https://espressif.github.io/esp-launchpad/js/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by igrr** [comment]
I think this is just an error which happens when you open the devtools, basically it's not finding the source-to-minified-source mapping for `bootstrap`. This shouldn't cause issues otherwise. Is the issue you are observing related to this specific error, or the actual operation of esp-launchpad?

**Comment by leeebo** [comment]
@igrr Now I have the following problem again, don't know what happened behind it. I am using https://espressif.github.io/esp-launchpad/?flashConfigURL=https://dl.espressif.com/AE/esp-box/esp_box_launch.toml, try to flash an ESP-BOX. 

![image](https://user-images.githubusercontent.com/16922815/221561820-e452e383-3b6f-4df0-ae2d-4a0a9078d909.png)

**Comment by leeebo** [comment]
I'm pretty sure that two days ago, there was no problem, and no modifications were made during that time 😢

**Comment by igrr** [comment]
From the backtrace it looks like the same issue as https://github.com/espressif/esp-launchpad/issues/18#issuecomment-1432867795 — it will be resolved once we make the next relase of esptool-js (the fix has already been merged there) and then update esptool-js version here.

**Comment by leeebo** [comment]
The duplicate issue https://github.com/espressif/esp-launchpad/issues/18, seems solved.
