### ISSUE TITLE
Add support for CH34x / CH9102F

### ISSUE THREAD

**Issue by georgik** [espressif/esp-launchpad#23]
Boards like LilyGO TTGO T5-4.7″ E-Paper or LilyGO TTGO T5 2.13" are using CH34x driver for communication.

After adding following code to `js/index.js`
```
const usbPortFilters = [
    { usbVendorId: 0x1a86, usbProductId: 0x55d4 },
```
the device appears in the list, but it's not able to connect. 

Console output looks like this:
```
esptool.js v0.1-dev
Serial port WebSerial VendorID 0x1a86 ProductID 0x55d4
Connecting.........._______......._______......._______.......
```

Drivers
- macOS: https://github.com/WCHSoftGroup/ch34xser_macos.
- older Windows 10: https://www.wch.cn/download/CH343SER_EXE.html.

On Linux the device is recognized as `/dev/ttyACMx`

**Comment by espzav** [comment]
Same for M5Stack:

- Core 1: CP210x (show in the list, but cannot connect)
- Core 2: CH9102 (not in the device list)

Drivers:
https://docs.m5stack.com/en/accessory/esp32_downloader_kit

**Comment by igrr** [comment]
I have tried CH9102F with esptool-js and found that it can't connect to it (neither with the default macOS driver nor with WCH driver), while esptool.py can.

**Comment by igrr** [comment]
Correction, _latest_ esptool-js actually can connect to CH9102F, at least on macOS, it just take a _really_ long time to do that:
```
Serial port WebSerial VendorID 0x1a86 ProductID 0x55d4
Connecting.........._______......._______......._______.
Detecting chip type... ESP32
Chip is ESP32-D0WD-V3 (revision 3)
```

**Comment by RushikeshPatange** [comment]
If anyone encounters timeout/ getting stuck issues while connecting or performing flash/erase operations with **CH34x/CH9102F**, please consider attempting these operations at a lower baud rate. Thank you!
