### ISSUE TITLE
Support flash ESP32 through brower in Android phone

### ISSUE THREAD

**Issue by leeebo** [espressif/esp-launchpad#26]
I found [Webusb is supported by Chrome in Android](https://caniuse.com/?search=Webusb), but testing with my phone (Android12 with Chrome 114) no USB device can be detected through Launchpad. Do you know if there is any problem there? Can we support such case?

**Comment by igrr** [comment]
Which USB/serial adapter are you using? Does your phone's kernel have the module for that adapter? I tried that a while ago and found that mine didn't have a module for CP2102. Maybe with S3 USB_SERIAL_JTAG it could work?

**Comment by leeebo** [comment]
No, I test with S3 USB_SERIAL_JTAG, also does not work. and also test with https://espressif.github.io/esptool-js/, nothing happens when I click the `connect` button. 🤔

**Comment by igrr** [comment]
@leeebo I'm sorry, I have misread your original comment. esptool-js uses WebSerial, not WebUSB. WebSerial is [not supported in Chrome for Android](https://caniuse.com/web-serial).

**Comment by leeebo** [comment]
@igrr Thanks for your explanation, any solution to achieve it? users want flash binary through Mobilphone USB.  [Using DFU](https://github.com/NordicSemiconductor/Android-DFU-Library)?
