### ISSUE TITLE
How to generate the Binary ?

### ISSUE THREAD

**Issue by franz-ms-muc** [espressif/esp-launchpad#5]
Hi, 

in https://espressif.github.io/esp-launchpad/config/config.toml you write: 
SINGLE_BIN_FOR_ESP32.bin

how to make this ? 

currently we get a bootloader.bin, a storage.bin, a Application.bin and so on ? 

Thanks, 
Franz

**Comment by liux-pro** [comment]
This may help.
```
idf.py build 
cd build 
esptool.py --chip esp32 merge_bin -o SINGLE_BIN_FOR_ESP32.bin @flash_args
```
